### ISSUE TITLE
 ipywidgets fails to install in jupyterlite/demo deployment with Pyodide kernel (3rd time) 

### ISSUE THREAD

**Issue by pierre-haessig** [jupyterlite/demo#138]
Hello,

This is, as far as I understand, the return of issues #97 and #127 about `ipywidgets` failing to install in the Jupyterlite demo deployment with Pyodide kernel.

## Reproduce

In the Jupyterlite demo, with the Pyodide kernel based notebook, running the cell magic

```
%pip install ipywidgets
```

(or its function based equivalent `await piplite.install(['ipywidgets'])`) yields an error:

```
ValueError: Can't find a pure Python 3 wheel for 'widgetsnbextension~=4.0.10'.
See: https://pyodide.org/en/stable/usage/faq.html#why-can-t-micropip-find-a-pure-python-wheel-for-a-package
You can use `await micropip.install(..., keep_going=True)` to get a list of all packages with missing wheels.
```

## Context

- JupyterLite version: latest version deployed in the demo. Looking at [requirements.txt](https://github.com/jupyterlite/demo/blob/main/requirements.txt), I see 

```
jupyterlite-core==0.2.3
jupyterlab~=4.0.11

# Python kernel (optional)
jupyterlite-pyodide-kernel==0.2.3

....
# Python: ipywidget library for Jupyter notebooks (optional)
ipywidgets>=8.1.1,<9
```

**Comment by jtpio** [comment]
@pierre-haessig normally this should have been fixed by the latest release of `jupyterlite-pyodide-kernel` and https://github.com/jupyterlite/demo/pull/135.

Just checked from https://jupyterlite.github.io/demo/lab/index.html and it looks good:

![image](https://github.com/jupyterlite/demo/assets/591645/1798d2fa-05db-43e4-884a-4aa429dcfc60)

**Comment by pierre-haessig** [comment]
Thanks for the fast feedback. Probably an error on my side since now it works also for me.

Normally I always erase the page data/cache before testing, but perhaps it wasn't erased when I made the test this afternoon. Unless something changed in a matter of 5 hours?

**Comment by jtpio** [comment]
Normally nothing changed since #135.

But this might become an issue again in the future when there is a new release of `ipywidgets`. Which requires updating the shims in `jupyterlite-pyodide-kernel`.

For reference you might also want to try the xeus python kernel (which also supports widgets) with https://jupyterlite-xeus.readthedocs.io/en/latest/ and the template: https://github.com/jupyterlite/xeus-python-demo. This kernel should not have that ipywidgets related issue.

**Comment by jtpio** [comment]
> since xeus-python can only be bundled with conda-forge packages, not just simple PyPI packages like mine.

`jupyterlite-xeus` has some basic support for installing packages from PyPI: https://jupyterlite-xeus.readthedocs.io/en/latest/environment.html#pip-packages

Although with some limitations (as described in the docs). But maybe it can still work with your simple package.
